# .Brewfile

brew "aqua"
brew "colima", restart_service: :changed
brew "curl"
brew "docker"
brew "docker-compose"
brew "gh"
brew "git"
brew "gnupg"
brew "jq"
brew "mise"
brew "ni"
brew "tilt"
brew "yq"

cask "copilot-cli"
cask "gcloud-cli"

vscode "aaron-bond.better-comments"
vscode "biomejs.biome"
vscode "eamodio.gitlens"
vscode "formulahendry.auto-close-tag"
vscode "formulahendry.auto-rename-tag"
vscode "github.copilot"
vscode "github.copilot-chat"
vscode "github.vscode-pull-request-github"
vscode "kingwl.vscode-vitest-runner"
vscode "marp-team.marp-vscode"
vscode "mikestead.dotenv"
vscode "ms-playwright.playwright"
vscode "ms-vscode.makefile-tools"
vscode "steoates.autoimport"
vscode "streetsidesoftware.code-spell-checker"
vscode "styled-components.vscode-styled-components"
vscode "vitest.explorer"
vscode "xabikos.javascriptsnippets"
vscode "yoavbls.pretty-ts-errors"
